In [1]:
list_1 =list(range(1,4))**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [5]:
import numpy as np
array_1 = np.arange(1, 4)**2
print(array_1)
array_2 = np.arange(1, 4)**3
print(array_2)
print(array_1+array_2)

[1 4 9]
[ 1  8 27]
[ 2 12 36]


In [8]:
print(np.power(np.array([1, 2, 3]), 4))

[ 1 16 81]


In [9]:
print(np.negative(np.array([1, 2, 3])))

[-1 -2 -3]


In [10]:
print(np.exp(np.array([1, 2, 3])))

[ 2.71828183  7.3890561  20.08553692]


In [11]:
print(np.log(np.array([1, 2, 3])))

[0.         0.69314718 1.09861229]


In [12]:
print(np.sin(np.array([1, 2, 3])))#only angles in radian

[0.84147098 0.90929743 0.14112001]


In [14]:
x=np.arange(3)
y=np.arange(3)
z=np.arange(3)
multi_array = np.array([x, y, z])
print(multi_array)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [15]:
print(multi_array.shape)

(3, 3)


In [17]:
print (np.linspace(1,10, 10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [18]:
print (np.linspace(1,10, 50))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [19]:
print (np.linspace(1,10, 100))

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [25]:
print(np.arange(1, 30, 4))

[ 1  5  9 13 17 21 25 29]


In [32]:
print(np.linspace(1, 10, 10, False)) #10 is excluded from the range

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [31]:
print(np.linspace(1, 10, 10, True))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [37]:
x=np.arange(3)
y=np.arange(3)
z=np.arange(3)
multi_array = np.array([x, y, z], dtype=np.int16)
print(multi_array.dtype)
multi_array = np.array([x, y, z], dtype=np.uint)
print(multi_array.dtype)

int16
uint32


In [43]:
x=np.arange(0,10)
print(x)
print(x[2:7])#index 7 is execluded
print(x[2:7:2])


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]


In [52]:
x= np.arange(9).reshape(3, 3)
print(x)
print(x[2, 1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
7


In [47]:
x= np.arange(9).reshape(3, -1) #-1 means choose number of rows automatically
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
x= np.arange(18).reshape(2, 3, 3) 
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [50]:
x= np.arange(18).reshape(3, 3, 2) 
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [86]:
x= np.arange(18).reshape(3, 2, 3) 
print(x)
print(x[1][0][:])
print(x[:][2][:])



[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
[6 7 8]
[[12 13 14]
 [15 16 17]]


In [89]:
comparison= x>5
print(comparison)
print(x[comparison])
print(x[x>5])

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]
[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [90]:
x.max()

17

In [91]:
x.min()

0

In [102]:
x=np.arange(9).reshape(3, 3)
print (x)
ravelled_array = x.ravel()
print(ravelled_array)
flattened_array = x.flatten()
print(flattened_array)



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [103]:
x[0][0]=10  #flattend is also changed
print (x)
print(ravelled_array)
print(flattened_array)

[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]
[10  1  2  3  4  5  6  7  8]
[0 1 2 3 4 5 6 7 8]


In [104]:
ravelled_array[0]=20
print (x)
print(ravelled_array)


[[20  1  2]
 [ 3  4  5]
 [ 6  7  8]]
[20  1  2  3  4  5  6  7  8]


In [110]:
y=np.arange(9)
y.shape=[3, 3]
print(y)
print(y.transpose())#changes the columns with rows
print(y.T)#same as transpose


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [113]:
print(np.resize(y, (6, 6)))

[[0 1 2 3 4 5]
 [6 7 8 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [114]:
print(np.zeros(5, dtype=int))

[0 0 0 0 0]


In [116]:
print(np.ones((3,2), dtype=int))

[[1 1]
 [1 1]
 [1 1]]


In [121]:
print (np.eye(3, dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [124]:
print(np.random.rand(4, 4))#0 <= random samples <= 1

[[0.31260954 0.61631409 0.62834288 0.25693009]
 [0.60975435 0.17481054 0.80417067 0.10300598]
 [0.80712022 0.77603083 0.7938082  0.65019807]
 [0.72220406 0.95402121 0.05590227 0.61013547]]


In [127]:
mat_a=np.matrix([0, 3, 5, 5, 5, 2]).reshape(2, 3)
print(mat_a)

[[0 3 5]
 [5 5 2]]


In [128]:
mat_b=np.matrix([3, 4, 3, 2, 4, 2]).reshape(3, 2)
print(mat_b)

[[3 4]
 [3 2]
 [4 2]]


In [132]:
print(mat_a*mat_b)
print(np.matmul(mat_a, mat_b))#same as above

[[29 16]
 [38 34]]
[[29 16]
 [38 34]]


In [134]:
mat_a=np.array([0, 3, 5, 5, 5, 2]).reshape(2, 3)
mat_b=np.array([3, 4, 3, 2, 4, 2]).reshape(3, 2)
#print(mat_a*mat_b)  #in order to do this they should be of the same size and the multiplication isn't like matrices
print(np.matmul(mat_a, mat_b))

[[29 16]
 [38 34]]


In [135]:
mat_a@mat_b # same as two methods

array([[29, 16],
       [38, 34]])

In [151]:
x=np.arange(4).reshape(2, 2)
y=np.arange(4, 8).reshape(2, 2)


In [144]:
#horizontally stacking
z=np.hstack((x,y))#should have the samme number of rows
print (z)
print(np.hstack((z, x)))# they have the same number of rows but different number of columns

[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5 0 1]
 [2 3 6 7 2 3]]


In [147]:
#vertically stacking
z=np.vstack((x,y))#should have the samme number of columns
print (z)


[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [158]:
#same as vstack
z=np.concatenate((x,y), axis=0)
print(z)
z=np.row_stack((x,y))
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [161]:
#same as hstack
z=np.concatenate((x,y), axis=1)
print(z)
z=np.column_stack((x,y))
print(z)
#these two differs in case of 1d array 
#hstack -> 1d
#column_stack -> 2d

[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]]


In [153]:
depth_stack=np.dstack((x, y))#stacks along the third dimension
print(depth_stack)

[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]
